const API_BASE=new URLSearchParams(location.search).get('api')||'http://localhost:8000';
const INDIA_BOUNDS=[[6.4,67.8],[37.7,97.7]];
const R=6378137,WORLD=2*Math.PI*R,ROOT_X=7570000,ROOT_Y=700000,ROOT_COLS=4000;
const BASE36='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ',LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ',DIGITS='0123456789';
const LEVELS=[{name:'1km2',label:'1 km²',side:1000,depth:0,zoom:7},{name:'0.01km2',label:'0.01 km²',side:100,depth:1,zoom:11},{name:'0.0001km2',label:'0.0001 km²',side:10,depth:2,zoom:15},{name:'1m2',label:'1 m²',side:1,depth:3,zoom:19},{name:'0.1m2',label:'0.1 m²',side:Math.sqrt(.1),depth:4,zoom:24}];
const TOKENS=[];for(const a of BASE36)for(const b of BASE36)if((/[A-Z]/.test(a)&&/\d/.test(b))||(/\d/.test(a)&&/[A-Z]/.test(b)))TOKENS.push(a+b);const TOKEN_TO_INDEX=new Map(TOKENS.slice(0,100).map((v,i)=>[v,i]));
// Ten deterministic terminal sample squares. They remain independent cells and are clipped to India.
const TERMINAL=[[0,0],[.34,0],[.68,0],[0,.34],[.34,.34],[.68,.34],[0,.68],[.34,.68],[.68,.68],[.315,.315]];
function b36(n,w){let s='';do{s=BASE36[n%36]+s;n=Math.floor(n/36)}while(n);return s.padStart(w,'0')}
function rootCode(ix,iy){const flat=iy*ROOT_COLS+ix,b=Math.floor(flat/36**4),r=flat%36**4;return LETTERS[Math.floor(b/10)]+DIGITS[b%10]+b36(r,4)}
function rootFromCode(code){if(!/^[A-Z]\d[0-9A-Z]{4}$/.test(code))throw Error('Invalid 6-character ALU root');let b=LETTERS.indexOf(code[0])*10+DIGITS.indexOf(code[1]),r=0;for(const c of code.slice(2))r=r*36+BASE36.indexOf(c);const flat=b*36**4+r;return {ix:flat%ROOT_COLS,iy:Math.floor(flat/ROOT_COLS)}}
function merc(lat,lon){lat=Math.max(-85.0511,Math.min(85.0511,lat));return [R*lon*Math.PI/180,R*Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))]}
function inv(x,y){return [180/Math.PI*(2*Math.atan(Math.exp(y/R))-Math.PI/2),180*x/(Math.PI*R)]}
function worldPx(z){return 256*2**z}
function screen(mx,my,z,o){const w=worldPx(z);return [(mx/WORLD+.5)*w-o.x,(.5-my/WORLD)*w-o.y]}
function pointRing(lat,lon,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const x1=ring[i][0],y1=ring[i][1],x2=ring[j][0],y2=ring[j][1],hit=((y1>lat)!=(y2>lat))&&(lon<(x2-x1)*(lat-y1)/(y2-y1)+x1);if(hit)inside=!inside}return inside}
function contains(lat,lon,f){const g=f.geometry;if(!g)return false;const poly=p=>pointRing(lat,lon,p[0])&&p.slice(1).every(r=>!pointRing(lat,lon,r));return g.type==='Polygon'?poly(g.coordinates):g.type==='MultiPolygon'?g.coordinates.some(poly):false}
function inIndia(lat,lon){return indiaGeometry.some(f=>contains(lat,lon,f))}
function pathRing(ctx,ring,z,o){if(!ring.length)return;let p=screen(...merc(ring[0][1],ring[0][0]),z,o);ctx.moveTo(p[0],p[1]);for(let i=1;i<ring.length;i++){p=screen(...merc(ring[i][1],ring[i][0]),z,o);ctx.lineTo(p[0],p[1])}ctx.closePath()}
function clipIndia(ctx,z,o){ctx.beginPath();for(const f of indiaGeometry){const g=f.geometry;if(g.type==='Polygon')for(const r of g.coordinates)pathRing(ctx,r,z,o);else if(g.type==='MultiPolygon')for(const p of g.coordinates)for(const r of p)pathRing(ctx,r,z,o)}ctx.clip('evenodd')}
function activeLevel(){let l=LEVELS[0];for(const x of LEVELS)if(map.getZoom()>=x.zoom)l=x;return l}
function visibleMerc(){const b=map.getBounds(),a=merc(b.getSouth(),b.getWest()),c=merc(b.getNorth(),b.getEast());return {minX:Math.min(a[0],c[0]),maxX:Math.max(a[0],c[0]),minY:Math.min(a[1],c[1]),maxY:Math.max(a[1],c[1])}}
function cellXY(level,gx,gy,k=-1){let x,y,side=level.side;if(level.depth<4){x=gx*side;y=gy*side}else{x=gx+TERMINAL[k][0];y=gy+TERMINAL[k][1];side=Math.sqrt(.1)}return [x,y,side]}
function paint(){if(!indiaGeometry.length)return;const size=map.getSize(),d=devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(size.x*d));canvas.height=Math.max(1,Math.floor(size.y*d));canvas.style.width=size.x+'px';canvas.style.height=size.y+'px';const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,size.x,size.y);const z=map.getZoom(),o=map.getPixelOrigin(),v=visibleMerc(),level=activeLevel(),unit=level.depth<4?level.side:1,r={minX:Math.floor((v.minX-unit*2)/unit),maxX:Math.ceil((v.maxX+unit*2)/unit),minY:Math.floor((v.minY-unit*2)/unit),maxY:Math.ceil((v.maxY+unit*2)/unit)};let total=(r.maxX-r.minX+1)*(r.maxY-r.minY+1)*(level.depth===4?10:1),step=total>16000?Math.ceil(Math.sqrt(total/16000)):1;ctx.save();clipIndia(ctx,z,o);ctx.strokeStyle='rgba(31,78,121,.48)';ctx.lineWidth=1;ctx.beginPath();if(level.depth<4){for(let gy=r.minY;gy<=r.maxY;gy+=step)for(let gx=r.minX;gx<=r.maxX;gx+=step){const [x,y,s]=cellXY(level,gx,gy),a=screen(x,y,z,o),b=screen(x+s,y+s,z,o),sx=Math.min(a[0],b[0]),sy=Math.min(a[1],b[1]),w=Math.abs(b[0]-a[0]),h=Math.abs(b[1]-a[1]);if(sx+w>=0&&sy+h>=0&&sx<=size.x&&sy<=size.y)ctx.rect(Math.round(sx)+.5,Math.round(sy)+.5,Math.max(1,w),Math.max(1,h))}}else{for(let gy=r.minY;gy<=r.maxY;gy++)for(let gx=r.minX;gx<=r.maxX;gx++)for(let k=0;k<10;k++){const [x,y,s]=cellXY(level,gx,gy,k),a=screen(x,y,z,o),b=screen(x+s,y+s,z,o),sx=Math.min(a[0],b[0]),sy=Math.min(a[1],b[1]),w=Math.abs(b[0]-a[0]),h=Math.abs(b[1]-a[1]);if(w>=.5&&sx+w>=0&&sy+h>=0&&sx<=size.x&&sy<=size.y)ctx.rect(Math.round(sx)+.5,Math.round(sy)+.5,Math.max(1,w),Math.max(1,h))}}ctx.stroke();ctx.restore()}
const map=L.map('map',{minZoom:5,maxZoom:25,zoomControl:true,maxBounds:INDIA_BOUNDS,maxBoundsViscosity:.95,zoomAnimation:true,fadeAnimation:false}).fitBounds(INDIA_BOUNDS);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,maxNativeZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
const boundaryLayer=L.geoJSON(null,{style:{weight:2,color:'#111827',fill:false,opacity:.9}}).addTo(map),highlightLayer=L.layerGroup().addTo(map);
const canvas=L.DomUtil.create('canvas','alu-grid-canvas');canvas.style.position='absolute';canvas.style.left='0';canvas.style.top='0';canvas.style.pointerEvents='none';canvas.style.zIndex='450';map.getPane('overlayPane').appendChild(canvas);
const tooltip=document.getElementById('cellTooltip'),searchInput=document.getElementById('aluSearch'),searchResult=document.getElementById('searchResult'),searchHint=document.getElementById('searchHint');let indiaGeometry=[],metaCache=new Map(),hoverToken=0,frame=0;
function schedule(){if(frame)return;frame=requestAnimationFrame(()=>{frame=0;paint()})} map.on('move zoom resize movestart zoomstart moveend zoomend',schedule);addEventListener('resize',schedule);
function codeFor(ix,iy,path){return [rootCode(ix,iy),...path.map(i=>TOKENS[i])].join('-')}
function cellAt(lat,lon){const level=activeLevel(),[mx,my]=merc(lat,lon),ix=Math.floor((mx-ROOT_X)/1000),iy=Math.floor((my-ROOT_Y)/1000);if(ix<0||iy<0||ix>=ROOT_COLS)return null;let lx=mx-(ROOT_X+ix*1000),ly=my-(ROOT_Y+iy*1000),side=1000,path=[];for(let d=0;d<level.depth;d++){if(d<3){const s=side/10,dx=Math.floor(lx/s),dy=Math.floor(ly/s);if(dx<0||dx>9||dy<0||dy>9)return null;path.push(dy*10+dx);lx-=dx*s;ly-=dy*s;side=s}else{const t=Math.sqrt(.1);let hit=-1;for(let k=0;k<10;k++){const p=TERMINAL[k];if(lx>=p[0]&&lx<=p[0]+t&&ly>=p[1]&&ly<=p[1]+t){hit=k;break}}if(hit<0)return null;path.push(hit)}}return {ix,iy,path,code:codeFor(ix,iy,path),level}}
function cellMercator(ix,iy,path){let x=ROOT_X+ix*1000,y=ROOT_Y+iy*1000,side=1000;for(let d=0;d<path.length;d++){const k=path[d];if(d<3){const s=side/10;x+=(k%10)*s;y+=Math.floor(k/10)*s;side=s}else{const p=TERMINAL[k];x+=p[0];y+=p[1];side=Math.sqrt(.1)}}return {x1:x,y1:y,x2:x+side,y2:y+side,side}}
map.on('mousemove',async e=>{if(!inIndia(e.latlng.lat,e.latlng.lng)){tooltip.classList.add('hidden');return}const h=cellAt(e.latlng.lat,e.latlng.lng);if(!h)return;tooltip.classList.remove('hidden');tooltip.style.left=Math.min(innerWidth-290,e.originalEvent.clientX+14)+'px';tooltip.style.top=Math.min(innerHeight-90,e.originalEvent.clientY+14)+'px';tooltip.innerHTML='<b>'+h.code+'</b><br>Area: '+(h.level.side*h.level.side)+' m²<br>ULPIN: checking…';const token=++hoverToken;if(metaCache.has(h.code)){const d=metaCache.get(h.code);tooltip.innerHTML='<b>'+h.code+'</b><br>Area: '+(d.area_m2??h.level.side*h.level.side)+' m²<br>ULPIN: '+(d.ulpin||'Not linked');return}try{const r=await fetch(API_BASE+'/api/v1/spatial/cell-info/'+encodeURIComponent(h.code));const d=r.ok?await r.json():{area_m2:h.level.side*h.level.side,ulpin:'Not linked'};metaCache.set(h.code,d);if(token===hoverToken)tooltip.innerHTML='<b>'+h.code+'</b><br>Area: '+(d.area_m2??h.level.side*h.level.side)+' m²<br>ULPIN: '+(d.ulpin||'Not linked')}catch(_){metaCache.set(h.code,{area_m2:h.level.side*h.level.side,ulpin:'Not linked'})}});
map.on('mouseout',()=>{tooltip.classList.add('hidden');hoverToken++});
function parseALU(v){const p=v.trim().toUpperCase().split('-').filter(Boolean);if(p.length<1||p.length>5)throw Error('Enter a 6-character root plus hierarchy segments');const root=rootFromCode(p[0]),path=p.slice(1).map(t=>{if(!TOKEN_TO_INDEX.has(t))throw Error('Invalid 2-character base36 hierarchy segment');return TOKEN_TO_INDEX.get(t)});if(path.length===4&&path[3]>=10)throw Error('Final level has 10 terminal children');return {ix:root.ix,iy:root.iy,path,code:p.join('-')}}
document.getElementById('aluSearchForm').addEventListener('submit',e=>{e.preventDefault();try{const t=parseALU(searchInput.value),c=cellMercator(t.ix,t.iy,t.path),ll=[[inv(c.x1,c.y1)[0],inv(c.x1,c.y1)[1]],[inv(c.x2,c.y2)[0],inv(c.x2,c.y2)[1]]];highlightLayer.clearLayers();L.rectangle(ll,{weight:4,color:'#ef4444',fill:false,dashArray:'8 6',interactive:false}).addTo(highlightLayer);searchResult.classList.remove('hidden');searchResult.innerHTML='<b>'+t.code+'</b><br>Hierarchical ALU cell';map.flyToBounds(ll,{duration:1.1,maxZoom:25})}catch(err){searchHint.textContent=err.message}});
async function loadBoundaries(){try{const r=await fetch(API_BASE+'/api/v1/spatial/india-boundaries');if(!r.ok)throw Error();const geo=await r.json();indiaGeometry=geo.features||[];boundaryLayer.addData(geo);schedule()}catch(_){searchHint.textContent='Map loaded. Start the backend to enable India boundary-aware cells.'}}
resizeCanvas=()=>{const s=map.getSize(),d=devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(s.x*d));canvas.height=Math.max(1,Math.floor(s.y*d));canvas.style.width=s.x+'px';canvas.style.height=s.y+'px'};resizeCanvas();schedule();loadBoundaries();