const API=(()=>{const q=new URLSearchParams(location.search).get('api');if(q)return q.replace(/\/$/,'');if(location.hostname.endsWith('.app.github.dev'))return `https://${location.hostname.replace(/-\d+\.app\.github\.dev$/,'-8000.app.github.dev')}`;return 'http://localhost:8000'})();
const STATUS={AVAILABLE:{cls:'green',label:'Green — AVAILABLE'},PARTIAL:{cls:'yellow',label:'Yellow — PARTIAL'},'N/D':{cls:'red',label:'Red — N/D'},'N/A':{cls:'gray',label:'Grey — N/A'}};
const TOKENS=[...('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ')].flatMap(a=>[...'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map(b=>a+b)).filter(t=>/[A-Z]/.test(t)&&/[0-9]/.test(t)).slice(0,100);
const TERMINAL_PLACEMENTS=[[0,0],[.34,0],[.68,0],[0,.34],[.34,.34],[.68,.34],[0,.68],[.34,.68],[.68,.68],[.315,.315]];
const TERMINAL_SIDE=.31622776601683794;
const map=L.map('map',{zoomControl:true,minZoom:15,maxZoom:22});
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:22,attribution:'© OpenStreetMap contributors'}).addTo(map);
let pilotBounds=null,level='1m2',cells=[],cellByKey=new Map(),canvas=null,ctx=null,raf=0;
function esc(v){return String(v??'N/D').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function metaStatus(s){return STATUS[s]||STATUS['N/A']}
function cssColor(s){return {green:'#22c55e',yellow:'#facc15',red:'#ef4444',gray:'#9ca3af'}[metaStatus(s).cls]}
async function getJson(path){const r=await fetch(API+path,{headers:{Accept:'application/json'}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}if(!r.ok)throw Error(d.detail||d.message||`HTTP ${r.status}`);return d}
function addControls(){const card=document.querySelector('.summary-card');const el=document.createElement('div');el.className='level-switch';el.innerHTML=`<div class="section-title" style="margin-top:12px">ALU display level</div><div class="level-buttons"><button data-level="1m2" class="active">1 m² · 10,000 ALUs</button><button data-level="0.1m2">0.1 m² · 100,000 logical ALUs</button></div>`;card.appendChild(el);el.querySelectorAll('button').forEach(b=>b.onclick=()=>switchLevel(b.dataset.level));}
function renderStats(meta){const c=meta.status_counts?.['1m2']||{};document.getElementById('stats').innerHTML=`<div class="stat"><b>${(meta.counts?.['1m2']||0).toLocaleString()}</b><span>1 m² ALUs</span></div><div class="stat"><b>${(meta.counts?.['0.1m2']||0).toLocaleString()}</b><span>0.1 m² logical</span></div><div class="stat"><b>${(c.AVAILABLE||0).toLocaleString()}</b><span>Green</span></div><div class="stat"><b>${(c.PARTIAL||0).toLocaleString()}</b><span>Yellow</span></div><div class="stat"><b>${(c['N/D']||0).toLocaleString()}</b><span>Red N/D</span></div><div class="stat"><b>${(c['N/A']||0).toLocaleString()}</b><span>Grey N/A</span></div>`}
function ensureCanvas(){if(canvas)return;canvas=document.createElement('canvas');canvas.className='alu-demo-canvas';canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:450;pointer-events:auto';document.querySelector('#map').appendChild(canvas);ctx=canvas.getContext('2d');window.addEventListener('resize',scheduleDraw)}
function resizeCanvas(){const r=map.getContainer().getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.floor(r.width)),h=Math.max(1,Math.floor(r.height));if(canvas.width!==Math.floor(w*d)||canvas.height!==Math.floor(h*d)){canvas.width=Math.floor(w*d);canvas.height=Math.floor(h*d)}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);return [w,h]}
function toMerc(lat,lng){const R=6378137,rad=Math.PI/180;return [R*lng*rad,R*Math.log(Math.tan(Math.PI/4+lat*rad/2))]}
function mercToContainer(x,y){const z=map.getZoom(),scale=256*Math.pow(2,z)/(2*Math.PI*6378137),center=map.getCenter(),cm=toMerc(center.lat,center.lng),r=map.getContainer().getBoundingClientRect();return {x:r.width/2+(x-cm[0])*scale,y:r.height/2-(y-cm[1])*scale}}
function cellMerc(row,col){const sw=toMerc(pilotBounds[0][0],pilotBounds[0][1]),ne=toMerc(pilotBounds[1][0],pilotBounds[1][1]);return [[sw[0]+(ne[0]-sw[0])*col/100,sw[1]+(ne[1]-sw[1])*row/100],[sw[0]+(ne[0]-sw[0])*(col+1)/100,sw[1]+(ne[1]-sw[1])*(row+1)/100]]}
function draw(){raf=0;if(!ctx||!pilotBounds||!cells.length)return;const [w,h]=resizeCanvas();const zoom=map.getZoom();ctx.lineWidth=.6;for(const item of cells){const b=cellMerc(item.row_index,item.col_index),sw=b[0],ne=b[1];if(level==='1m2'){const a=mercToContainer(sw[0],sw[1]),z=mercToContainer(ne[0],ne[1]),x=a.x,y=z.y,ww=z.x-a.x,hh=a.y-z.y;if(x>w||y>h||x+ww<0||y+hh<0)continue;ctx.globalAlpha=.62;ctx.fillStyle=cssColor(item.status);ctx.fillRect(x,y,Math.max(1,ww),Math.max(1,hh));if(ww>2){ctx.globalAlpha=.35;ctx.strokeStyle='#334155';ctx.strokeRect(x,y,ww,hh)}}else if(zoom>=17){const sideX=ne[0]-sw[0],sideY=ne[1]-sw[1];for(let t=0;t<10;t++){const [ox,oy]=TERMINAL_PLACEMENTS[t],tsw=[sw[0]+ox*sideX,sw[1]+oy*sideY],tne=[tsw[0]+TERMINAL_SIDE*sideX,tsw[1]+TERMINAL_SIDE*sideY];const a=mercToContainer(tsw[0],tsw[1]),z=mercToContainer(tne[0],tne[1]),x=a.x,y=z.y,ww=z.x-a.x,hh=a.y-z.y;if(x>w||y>h||x+ww<0||y+hh<0)continue;const tstatus=(t===9&&item.status==='AVAILABLE')?'PARTIAL':(t===7&&item.status==='PARTIAL'?'N/D':(t===5&&item.status==='N/D'?'N/A':item.status));ctx.globalAlpha=.58;ctx.fillStyle=cssColor(tstatus);ctx.fillRect(x,y,Math.max(1,ww),Math.max(1,hh));if(ww>4){ctx.globalAlpha=.3;ctx.strokeStyle='#334155';ctx.strokeRect(x,y,ww,hh)}}}}ctx.globalAlpha=1;}
function scheduleDraw(){if(!raf)raf=requestAnimationFrame(draw)}
function openDetails(detail){const old=document.getElementById('aluDetailModal');if(old)old.remove();const s=metaStatus(detail.overall_status);const modal=document.createElement('div');modal.id='aluDetailModal';modal.className='alu-detail-modal';modal.innerHTML=`<div class="alu-detail-backdrop"></div><div class="alu-detail-panel"><button class="alu-detail-close" aria-label="Close">×</button><div class="alu-detail-head"><div><div class="alu-detail-kicker">ALU DETAILS · PUNE PILOT</div><h2>${esc(detail.alu)}</h2><p>${esc(detail.grid_level)} · deterministic project spatial index</p></div><span class="pill ${s.cls}">${esc(s.label)}</span></div><div class="alu-parent"><div><b>Parent ULPIN</b><strong>${esc(detail.ulpin)}</strong></div><span>Demo reference only — no government ULPIN imported</span></div><div class="alu-meta"><div><b>Location</b><span>${esc(detail.location.locality)}, ${esc(detail.location.district)}, ${esc(detail.location.state)}</span></div><div><b>ALU ID</b><span>${esc(detail.alu)}</span></div><div><b>Grid Level</b><span>${esc(detail.grid_level)}</span></div><div><b>Coordinates</b><span>${esc(detail.location.lat)}° N · ${esc(detail.location.lng)}° E</span></div><div><b>Display tolerance</b><span>${esc(detail.accuracy)}</span></div><div><b>AI confidence</b><span>${esc(detail.ai_confidence)}</span></div></div><div class="alu-fields">${detail.fields.map(f=>{const shown=f.status==='N/D'?'N/D — not publicly verified':f.status==='N/A'?'N/A — not applicable':f.value;return `<article class="alu-field ${esc(metaStatus(f.status).cls)}"><div class="alu-field-top"><b>${esc(f.label)}</b><span class="pill ${metaStatus(f.status).cls}">${esc(f.status)}</span></div><div class="alu-field-value">${esc(shown).replace(/\n/g,'<br>')}</div><small>${esc(f.source)}</small></article>`}).join('')}</div><div class="alu-demo-note">${esc(detail.note)}</div></div>`;document.body.appendChild(modal);modal.querySelector('.alu-detail-backdrop').onclick=()=>modal.remove();modal.querySelector('.alu-detail-close').onclick=()=>modal.remove()}
function showLoading(){document.getElementById('detail').innerHTML='<div class="empty">Loading complete ALU record…</div>'}
async function showAlu(aluId){showLoading();try{const d=await getJson(`/api/v1/pune-demo/alu-catalog/cells/${encodeURIComponent(aluId)}/details`);openDetails(d);document.getElementById('detail').innerHTML=`<div class="selected-head"><strong>${esc(d.alu)}</strong><span class="pill ${metaStatus(d.overall_status).cls}">${esc(metaStatus(d.overall_status).label)}</span></div><div class="cell-note">21 demo information fields are available for this ALU. The full view opened over the map.</div>`}catch(e){document.getElementById('detail').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function parentAt(latlng){const m=toMerc(latlng.lat,latlng.lng),sw=toMerc(pilotBounds[0][0],pilotBounds[0][1]),ne=toMerc(pilotBounds[1][0],pilotBounds[1][1]);const col=Math.floor((m[0]-sw[0])/((ne[0]-sw[0])/100)),row=Math.floor((m[1]-sw[1])/((ne[1]-sw[1])/100));if(row<0||row>=100||col<0||col>=100)return null;return cellByKey.get(`${row}:${col}`)||null}
function selectedAlu(latlng){const item=parentAt(latlng);if(!item)return null;if(level==='1m2')return item.alu_id;const m=toMerc(latlng.lat,latlng.lng),b=cellMerc(item.row_index,item.col_index),dx=(m[0]-b[0][0])/(b[1][0]-b[0][0]),dy=(m[1]-b[0][1])/(b[1][1]-b[0][1]);let best=0,bd=Infinity;for(let i=0;i<10;i++){const [ox,oy]=TERMINAL_PLACEMENTS[i],d=(dx-ox)**2+(dy-oy)**2;if(d<bd){bd=d;best=i}}return `${item.alu_id}-${TOKENS[best]}`}
async function switchLevel(next){level=next;document.querySelectorAll('.level-buttons button').forEach(b=>b.classList.toggle('active',b.dataset.level===level));document.getElementById('detail').innerHTML='<div class="empty">Loading ALU display…</div>';try{const d=await getJson('/api/v1/pune-demo/alu-catalog/cells?level=1m2&limit=10000');cells=d.items||[];cellByKey=new Map(cells.map(x=>[`${x.row_index}:${x.col_index}`,x]));scheduleDraw();document.getElementById('detail').innerHTML=`<div class="empty">${next==='1m2'?'10,000 1 m² ALU cells are active on the pilot map.':'100,000 logical 0.1 m² ALU children are available. Zoom further in to see their child cells.'}<br><br>Click any coloured ALU cell to open all 21 information fields.</div>`}catch(e){document.getElementById('detail').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function init(){ensureCanvas();try{const meta=await getJson('/api/v1/pune-demo/alu-catalog');pilotBounds=meta.bbox;renderStats(meta);addControls();map.fitBounds(pilotBounds,{padding:[80,80]});L.rectangle(pilotBounds,{color:'#7f1d1d',weight:2,dashArray:'7 6',fill:false,interactive:false}).addTo(map);await switchLevel('1m2');map.on('move zoom resize',scheduleDraw);canvas.addEventListener('click',e=>{const r=map.getContainer().getBoundingClientRect();const point=map.containerPointToLatLng([e.clientX-r.left,e.clientY-r.top]);const id=selectedAlu(point);if(id)showAlu(id)});setTimeout(scheduleDraw,200)}catch(e){document.getElementById('stats').innerHTML='<div class="empty">ALU catalog unavailable</div>';document.getElementById('detail').innerHTML=`<div class="empty">${esc(e.message)}<br><br>Start PostgreSQL/PostGIS, seed the ALU catalog, then restart FastAPI.</div>`}}
init();