const API=(()=>{const q=new URLSearchParams(location.search).get('api');if(q)return q.replace(/\/$/,'');if(location.hostname.endsWith('.app.github.dev'))return `https://${location.hostname.replace(/-\d+\.app\.github\.dev$/,'-8000.app.github.dev')}`;return 'http://localhost:8000'})();
const STATUS={GREEN:{cls:'green',label:'Green — 19–21 / 21 fields'},YELLOW:{cls:'yellow',label:'Yellow — 15–18 / 21 fields'},RED:{cls:'red',label:'Red — <15 / 21 fields'},WHITE:{cls:'white',label:'White — not searched / controversial boundary'}};
const TOKENS=[...'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'].flatMap(a=>[...'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map(b=>a+b)).filter(t=>/[A-Z]/.test(t)&&/[0-9]/.test(t)).slice(0,100);
const TERMINAL_PLACEMENTS=[[0,0],[.34,0],[.68,0],[0,.34],[.34,.34],[.68,.34],[0,.68],[.34,.68],[.68,.68],[.315,.315]];
const TERMINAL_SIDE=Math.sqrt(.1);
const DEFAULT_BOUNDS=[[18.5069,73.8072],[18.5079,73.8082]];
const map=L.map('map',{zoomControl:true,minZoom:15,maxZoom:22,center:[18.5074,73.8077],zoom:18});
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:22,attribution:'© OpenStreetMap contributors'}).addTo(map);
let pilotBounds=DEFAULT_BOUNDS,level='1m2',cells=[],cellByKey=new Map(),canvas=null,ctx=null,raf=0;
function esc(v){return String(v??'N/D').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusMeta(s){return STATUS[s]||STATUS.RED}
function statusColor(s){return {green:'#22c55e',yellow:'#facc15',red:'#ef4444',white:'#fff'}[statusMeta(s).cls]}
async function getJson(path){const r=await fetch(API+path,{headers:{Accept:'application/json'},cache:'force-cache'});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}if(!r.ok)throw Error(d.detail||d.message||`HTTP ${r.status}`);return d}
function addControls(){const card=document.querySelector('.summary-card');const el=document.createElement('div');el.className='level-switch';el.innerHTML=`<div class="section-title" style="margin-top:12px">ALU display level</div><div class="level-buttons"><button data-level="1m2" class="active">1 m² · 10,000 ALUs</button><button data-level="0.1m2">0.1 m² · 100,000 logical ALUs</button></div>`;card.appendChild(el);el.querySelectorAll('button').forEach(b=>b.onclick=()=>switchLevel(b.dataset.level));}
function renderStats(meta){const c=meta.status_counts||{GREEN:0,YELLOW:0,RED:0,WHITE:0};document.getElementById('stats').innerHTML=`<div class="stat"><b>${(meta.count||10000).toLocaleString()}</b><span>1 m² ALUs</span></div><div class="stat"><b>100,000</b><span>0.1 m² logical</span></div><div class="stat"><b>${(c.GREEN||0).toLocaleString()}</b><span>Green · 19–21</span></div><div class="stat"><b>${(c.YELLOW||0).toLocaleString()}</b><span>Yellow · 15–18</span></div><div class="stat"><b>${(c.RED||0).toLocaleString()}</b><span>Red · &lt;15</span></div><div class="stat"><b>${(c.WHITE||0).toLocaleString()}</b><span>White · pending</span></div>`}
function ensureCanvas(){if(canvas)return;canvas=document.createElement('canvas');canvas.className='alu-demo-canvas';canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:450;pointer-events:auto';document.querySelector('#map').appendChild(canvas);ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});window.addEventListener('resize',scheduleDraw,{passive:true})}
function resizeCanvas(){const s=map.getSize(),d=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.floor(s.x)),h=Math.max(1,Math.floor(s.y));if(canvas.width!==Math.floor(w*d)||canvas.height!==Math.floor(h*d)){canvas.width=Math.floor(w*d);canvas.height=Math.floor(h*d)}ctx.setTransform(d,0,0,d,0,0);return [w,h]}
function toMerc(lat,lng){const R=6378137,rad=Math.PI/180;return [R*lng*rad,R*Math.log(Math.tan(Math.PI/4+lat*rad/2))]}
function mercToContainer(x,y){const z=map.getZoom(),scale=256*Math.pow(2,z)/(2*Math.PI*6378137),center=map.getCenter(),cm=toMerc(center.lat,center.lng),r=map.getContainer().getBoundingClientRect();return {x:r.width/2+(x-cm[0])*scale,y:r.height/2-(y-cm[1])*scale}}
function cellMerc(row,col){const sw=toMerc(pilotBounds[0][0],pilotBounds[0][1]),ne=toMerc(pilotBounds[1][0],pilotBounds[1][1]),dx=(ne[0]-sw[0])/100,dy=(ne[1]-sw[1])/100;return [[sw[0]+col*dx,sw[1]+row*dy],[sw[0]+(col+1)*dx,sw[1]+(row+1)*dy]]}
function draw(){raf=0;if(!ctx||!pilotBounds||!cells.length)return;const [w,h]=resizeCanvas();const zoom=map.getZoom();ctx.clearRect(0,0,w,h);const sw=toMerc(pilotBounds[0][0],pilotBounds[0][1]),ne=toMerc(pilotBounds[1][0],pilotBounds[1][1]);const nw=mercToContainer(sw[0],ne[1]),se=mercToContainer(ne[0],sw[1]);const cw=(se.x-nw.x)/100,ch=(se.y-nw.y)/100;if(cw<=0||ch<=0)return;if(zoom<17){ctx.globalAlpha=.18;ctx.strokeStyle='#b45309';ctx.setLineDash([7,5]);ctx.lineWidth=2;ctx.strokeRect(nw.x,nw.y,se.x-nw.x,se.y-ne.y);ctx.setLineDash([]);ctx.globalAlpha=1;return}for(const item of cells){const x=nw.x+item.col*cw,y=nw.y+item.row*ch;if(x>w||y>h||x+cw<0||y+ch<0)continue;ctx.globalAlpha=.64;ctx.fillStyle=statusColor(item.status);ctx.fillRect(x,y,Math.max(1,cw+.2),Math.max(1,ch+.2));if(cw>=3){ctx.globalAlpha=.28;ctx.strokeStyle='#334155';ctx.lineWidth=.45;ctx.strokeRect(x,y,cw,ch)}}ctx.globalAlpha=1}
function scheduleDraw(){if(!raf)raf=requestAnimationFrame(draw)}
function openDetails(detail){const old=document.getElementById('aluDetailModal');if(old)old.remove();const status=statusMeta(detail.coverage_status||'RED');const available=detail.available_fields??0;const modal=document.createElement('div');modal.id='aluDetailModal';modal.className='alu-detail-modal';modal.innerHTML=`<div class="alu-detail-backdrop"></div><div class="alu-detail-panel"><button class="alu-detail-close" aria-label="Close">×</button><div class="alu-detail-head"><div><div class="alu-detail-kicker">ALU DETAILS · PUNE PILOT</div><h2>${esc(detail.alu)}</h2><p>${esc(detail.grid_level)} · deterministic project spatial index</p></div><span class="pill ${status.cls}">${esc(status.label)}</span></div><div class="coverage-score"><strong>${available}/21 fields available</strong><span>${esc(status.label)}</span><small>Only N/D and N/A fields are excluded from the coverage score.</small></div><div class="alu-parent"><div><b>Parent ULPIN</b><strong>${esc(detail.ulpin)}</strong></div><span>Government ULPIN is N/D in this demo because no official ULPIN was imported.</span></div><div class="alu-meta"><div><b>Location</b><span>${esc(detail.location.locality)}, ${esc(detail.location.district)}, ${esc(detail.location.state)}</span></div><div><b>ALU ID</b><span>${esc(detail.alu)}</span></div><div><b>Grid Level</b><span>${esc(detail.grid_level)}</span></div><div><b>Coordinates</b><span>${esc(detail.location.lat)}° N · ${esc(detail.location.lng)}° E</span></div><div><b>Display tolerance</b><span>${esc(detail.accuracy)}</span></div><div><b>AI confidence</b><span>${esc(detail.ai_confidence)}</span></div></div><div class="alu-fields">${(detail.fields||[]).map(f=>{const c=f.status==='N/D'?'red':f.status==='N/A'?'gray':'green';const shown=f.status==='N/D'?'N/D — not publicly verified':f.status==='N/A'?'N/A — not applicable':f.value;return `<article class="alu-field ${c}"><div class="alu-field-top"><b>${esc(f.label)}</b><span class="pill ${c}">${esc(f.status)}</span></div><div class="alu-field-value">${esc(shown).replace(/\n/g,'<br>')}</div><small>${esc(f.source)}</small></article>`}).join('')}</div><div class="alu-demo-note">${esc(detail.note)}</div></div>`;document.body.appendChild(modal);modal.querySelector('.alu-detail-backdrop').onclick=()=>modal.remove();modal.querySelector('.alu-detail-close').onclick=()=>modal.remove()}
async function showAlu(aluId){document.getElementById('detail').innerHTML='<div class="empty">Loading complete 21-field ALU record…</div>';try{const d=await getJson(`/api/v1/pune-demo/alu-catalog/cells/${encodeURIComponent(aluId)}/details`);openDetails(d);document.getElementById('detail').innerHTML=`<div class="selected-head"><strong>${esc(d.alu)}</strong><span class="pill ${statusMeta(d.coverage_status).cls}">${esc(statusMeta(d.coverage_status).label)}</span></div><div class="cell-note">${esc(d.available_fields)}/21 fields are not N/D or N/A. The full record is open over the map.</div>`}catch(e){document.getElementById('detail').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function cellAt(latlng){if(!pilotBounds)return null;const b=pilotBounds,m=toMerc(latlng.lat,latlng.lng),sw=toMerc(b[0][0],b[0][1]),ne=toMerc(b[1][0],b[1][1]);if(m[0]<sw[0]||m[0]>ne[0]||m[1]<sw[1]||m[1]>ne[1])return null;const col=Math.max(0,Math.min(99,Math.floor((m[0]-sw[0])/(ne[0]-sw[0])*100)));const row=Math.max(0,Math.min(99,Math.floor((m[1]-sw[1])/(ne[1]-sw[1])*100)));return cellByKey.get(`${row}:${col}`)||null}
function selectedAlu(latlng){const item=cellAt(latlng);if(!item)return null;if(level==='1m2'||map.getZoom()<19)return item.alu_id;const b=cellMerc(item.row_index,item.col_index),m=toMerc(latlng.lat,latlng.lng),dx=(m[0]-b[0][0])/(b[1][0]-b[0][0]),dy=(m[1]-b[0][1])/(b[1][1]-b[0][1]);let best=0,dist=Infinity;for(let i=0;i<10;i++){const [ox,oy]=TERMINAL_PLACEMENTS[i],d=(dx-ox)**2+(dy-oy)**2;if(d<dist){dist=d;best=i}}return `${item.alu_id}-${TOKENS[best]}`}
async function switchLevel(next){level=next;document.querySelectorAll('.level-buttons button').forEach(b=>b.classList.toggle('active',b.dataset.level===level));document.getElementById('detail').innerHTML=`<div class="empty">${next==='1m2'?'10,000 1 m² ALUs are displayed and clickable.':'100,000 logical 0.1 m² children are available inside those 1 m² ALUs; zoom further in to inspect them.'}<br><br>Cell colour is calculated from the 21 ALU information fields.</div>`;scheduleDraw()}
async function init(){ensureCanvas();addControls();try{const data=await getJson('/api/v1/pune-demo/alu-catalog/coverage-grid?level=1m2');pilotBounds=data.bbox||DEFAULT_BOUNDS;cells=data.items||[];cellByKey=new Map(cells.map(x=>[`${x.row}:${x.col}`,x]));renderStats(data);map.fitBounds(pilotBounds,{padding:[75,75],animate:false});L.rectangle(pilotBounds,{color:'#7f1d1d',weight:2,dashArray:'7 6',fill:false,interactive:false}).addTo(map);await switchLevel('1m2');map.on('move zoom resize',scheduleDraw);canvas.addEventListener('click',e=>{const r=map.getContainer().getBoundingClientRect();const pt=map.containerPointToLatLng([e.clientX-r.left,e.clientY-r.top]);const id=selectedAlu(pt);if(id)showAlu(id)});const q=new URLSearchParams(location.search).get('alu');if(q)setTimeout(()=>showAlu(q),250);setTimeout(scheduleDraw,100)}catch(e){document.getElementById('stats').innerHTML='<div class="empty">Pune ALU demo could not load</div>';document.getElementById('detail').innerHTML=`<div class="empty">${esc(e.message)}<br><br>The map is still available at the Kothrud pilot location. Start FastAPI on port 8000 to load ALU coverage and details.</div>`}}
init();
