const API_BASE = new URLSearchParams(location.search).get('api') || 'http://localhost:8000';
export async function api(path){const r=await fetch(API_BASE+path,{headers:{Accept:'application/json'}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}if(!r.ok)throw Error(d.detail||d.message||`HTTP ${r.status}`);return d}
export const esc=v=>String(v??'N/D').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=k=>k.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const flat=(o,p='')=>Object.entries(o||{}).flatMap(([k,v])=>v&&typeof v==='object'&&!Array.isArray(v)?flat(v,p?`${p}.${k}`:k):[[p?`${p}.${k}`:k,Array.isArray(v)?v.join(', '):v]]);
function nav(active){const xs=[['land_records','Land Records'],['registration','Registration'],['planning_building','Planning & Building'],['property_tax','Property Tax'],['utilities_infrastructure','Utilities'],['legal_encumbrance','Legal / Encumbrance'],['citizen_land_services','Citizen Land Services']];return `<nav>${xs.map(x=>`<a class="${x[0]===active?'active':''}" href="../${x[0]}/">${x[1]}</a>`).join('')}</nav>`}
function sourceBlock(r){const rows=flat(r.data).slice(0,28).map(([k,v])=>`<tr><th>${esc(pretty(k))}</th><td>${esc(v)}</td></tr>`).join('');return `<section class="card"><div class="cardhead"><b>${esc(r.record_id||'DEMO RECORD')}</b><span>${esc(r.status||'AVAILABLE')}</span><em>FICTIONAL</em></div><table>${rows}</table><small>Source: ${esc(r.source?.source_name)} · ${esc(r.source?.source_url)}</small></section>`}
export function mountPortal(c){document.title=c.title;const app=document.getElementById('portalApp');app.innerHTML=`<div class="banner"><b>DEMO SYSTEM</b> · FICTIONAL RECORD DATA · PUBLIC-GEOGRAPHY REFERENCES · NOT AN OFFICIAL GOVERNMENT WEBSITE</div><header><div><h1>${esc(c.title)}</h1><p>${esc(c.subtitle)}</p></div><div class="mark">DEMO<br>PORTAL</div></header>${nav(c.service)}<main><section class="notice"><b>Notice:</b> This site reproduces publicly observable workflow structures. Names, amounts, document numbers and other record attributes are fictional.</section><section class="panel"><h2>${esc(c.searchTitle||'Search Records')}</h2><div class="fields">${c.fields.map(f=>`<label>${esc(f.label)}<input data-k="${esc(f.key)}" placeholder="${esc(f.placeholder||'')}" /></label>`).join('')}</div><button id="go">Search</button> <button id="reset" class="secondary">Reset</button><div id="msg"></div></section><h2>Results</h2><div id="results" class="results">Enter a demo search value.</div></main>`;
const vals=()=>c.fields.map(f=>document.querySelector(`[data-k="${CSS.escape(f.key)}"]`).value.trim()).filter(Boolean).join(' ');const renderList=async()=>{const results=document.getElementById('results');results.textContent='Searching…';try{const d=await api(`/api/v1/pune-demo/search?q=${encodeURIComponent(vals())}&service=${encodeURIComponent(c.service)}`);if(!d.results?.length){results.innerHTML='<div class="empty">No record found for the selected criteria.</div>';return}results.innerHTML=d.results.map(x=>`<div class="result"><div><b>${esc(x.parcel_id)}</b><span>${esc(x.survey_number)} · ${esc(x.cts_number)}</span></div><button data-id="${esc(x.parcel_id)}">View Record</button></div>`).join('');results.querySelectorAll('button').forEach(b=>b.onclick=()=>open(b.dataset.id))}catch(e){results.innerHTML=`<div class="error">${esc(e.message)}</div>`}};
const open=async id=>{const results=document.getElementById('results');results.textContent='Loading…';try{const d=await api(`/api/v1/pune-demo/parcels/${encodeURIComponent(id)}`),p=d.parcel;let html=`<section class="card"><div class="cardhead"><b>${esc(p.parcel_id)}</b><span>${esc(p.data_status)}</span><em>FICTIONAL</em></div><table>${[['District',p.district],['Taluka / Office',p.taluka],['Locality / Peth',p.locality],['Survey / Gat',p.survey_number],['Hissa',p.hissa_number],['CTS',p.cts_number],['Property UID',p.property_uid],['ULPIN',p.ulpin||'N/D'],['Area',`${p.area_m2} m² (demo attribute)`],['Geometry',p.geometry?'AVAILABLE':'N/D'],['Geometry status',p.geometry_status],['ALU',d.alu?.alu_id||'N/D — geometry not linked']].map(x=>`<tr><th>${esc(x[0])}</th><td>${esc(x[1])}</td></tr>`).join('')}</table></section>`;html+=Object.entries(d.categories||{}).map(([k,v])=>`<details><summary>${esc(pretty(k))} <span>${esc(v.status)}</span></summary>${sourceBlock({record_id:v.record_id,status:v.status,source:v.source,data:v.payload})}</details>`).join('');html+=`<details class="api"><summary>View API Response</summary><pre>${esc(JSON.stringify(d,null,2))}</pre></details>`;results.innerHTML=html}catch(e){results.innerHTML=`<div class="error">${esc(e.message)}</div>`}};
document.getElementById('go').onclick=renderList;document.getElementById('reset').onclick=()=>{c.fields.forEach(f=>document.querySelector(`[data-k="${CSS.escape(f.key)}"]`).value='');document.getElementById('results').innerHTML='Enter a demo search value.'}}
